when:
  - event: [push, cron, manual]
    branch: main

matrix:
  # renovate: datasource=github-releases depName=actions/runner extractVersion=^v(?<version>.*)$
  RUNNER_VERSION:
    - 2.311.0
  NAME:
    - alpine-rootful
    - alpine-rootless
    - ubuntu-rootful
    - ubuntu-rootless

steps:
  "Build and publish image":
    image: woodpeckerci/plugin-docker-buildx:2.2.1
    secrets: [dockerhub_token_cynkragmbh]
    # environment:
    #   - RUNNER_VERSION=2.311.0
    settings:
      dockerfile: images/Dockerfile-${NAME}
      repo: cynkra/actions-runner
      username: cynkragmbh
      tags: ${RUNNER_VERSION}-${NAME},${RUNNER_VERSION:0:1}-${NAME}
      platforms: linux/amd64,linux/arm64
      password:
        from_secret: dockerhub_token_cynkragmbh
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 500Mi
            cpu: 800m
          limits:
            memory: 700Mi
            cpu: 2000m
